### ISSUE TITLE
Feature: Option to display Meeting Room in menu bar and/or in list view

### ISSUE THREAD

**Issue by fatihkurtoglu** [leits/MeetingBar#629] opened 2023-06-27 22:23 UTC
### Issue that this suggestion fixes

I know the focus of this app is mainly for online meetings but as many companies migrate to hybrid or RTO approach, we start to have on-site meetings as well. I want to use Meeting Bar as "the" calendar view for day to day, but in order to get meeting room details, I need to switch back to GCal to get more details. 

### Solution description

I want to be able to quickly see the assigned meeting room(s) for the incoming meeting, either in the menu bar, or in the list view, without going into the event details page.

In gCal, Rooms are assigned separately as a meeting location, so having an option in the tool to allow displaying meeting room next to the title, would be helpful for to achieve that.

### Alternatives considered

Today workaroun is to enable "details as submenu" and having to check details view, and try to get "room" information from the "Location" section. It requies a few steps to go there and find by eye.

**Comment by leits** [comment] 2023-07-05 19:25
Thanks for the request @fatihkurtoglu!

I'll close this issue as a duplicate of #368. Stay tuned to that ticket.

**Closed by leits** 2023-07-05 19:25 UTC
Labels: duplicate, feature
