### ISSUE TITLE
Bug: Expanding Menubar Icon Spacing

### ISSUE THREAD

**Issue by mB-PiBox** [leits/MeetingBar#413] opened 2022-02-06 15:55 UTC
When preference for Appearance>Show event for: is set to "today & tomorrow" it expands menubar icon spacing of all apps.
<img width="2056" alt="Screen Shot 2022-02-06 at 9 52 48 AM" src="https://user-images.githubusercontent.com/14003870/152689224-b02987e0-9d29-4c1a-82d0-f9dc5448ab16.png">
<img width="2056" alt="Screen Shot 2022-02-06 at 9 53 23 AM" src="https://user-images.githubusercontent.com/14003870/152689230-3d278888-0814-4445-b818-046ae5bf8032.png">

**Comment by jgoldhammer** [comment] 2022-03-22 21:31
Hi  @mB-PiBox 

How can I reproduce it? I have tried several times and could not reproduce locally.
Which version are you using?

Thanks,
Jens

**Comment by mB-PiBox** [comment] 2022-03-23 07:20
> Hi @mB-PiBox
> 
> How can I reproduce it? I have tried several times and could not reproduce locally. Which version are you using?
> 
> Thanks, Jens

Due to the issue; I've since uninstall "MeetingBar" over a month ago.. 
move to just using Alfred workflow to check upcoming meetings & get video conference link.

**Comment by 0bmxa** [comment] 2022-04-01 13:35
@mB-PiBox are you by any chance using an app which controls which menu bar items are currently visible, or adds an overflow menu?

**Comment by jgoldhammer** [comment] 2022-04-03 15:59
Closing the ticket as this cannot be reproduced with Bartender or Dozer...

**Closed by jgoldhammer** 2022-04-03 15:59 UTC
Labels: bug

**Comment by mB-PiBox** [comment] 2022-04-04 02:17
> @mB-PiBox are you by any chance using an app which controls which menu bar items are currently visible, or adds an overflow menu?

Yes, sorta. I have "Hidden Bar" running, which allows the to determine/set which menu bar items are hidden to the left of the  arrow.. It doesn't control thing what is or isn't, I do.


> Closing the ticket as this cannot be reproduced with Bartender or Dozer...

This is the dumbest reason to close a bug; because you used to overpriced apps, and wasn't able to get off, then the bug is irrelevent? GTFO!
