### ISSUE TITLE
Feature: Open calendar event when clicking it instead of trying to open meeting

### ISSUE THREAD

**Issue by rosenpin** [leits/MeetingBar#345] opened 2021-09-21 10:53 UTC
**Is your feature request related to a problem? Please describe.**
Most of my events are not Zoom/Google meet meetings, but things that I should do/be at/attend to.  
Intuitively, I try to click the event to get more information (location/exact time) or edit it, but instead of being able to open the event in Google Calendar for example, I just get an error saying my meeting service is not supported 
<img width="268" alt="image" src="https://user-images.githubusercontent.com/5289630/134158278-ea5f179c-0506-416c-b3f2-16c1abb4c380.png">

**Describe the solution you'd like**
Add a select option in settings like "Click event to..." with a drop down menu including the following options:  
- Join meeting
- Open in Calendar app
- Open in Google Calendar

An even better solution will be to try to join meeting, and if it fails just open the event instead of showing an error message

**Comment by leits** [comment] 2022-10-14 19:26
Hi @rosenpin,
Thanks for the request. It works this way by design and because there are no thumbs up from other people I'll close the issue. Sorry, I don't want to make the app overcomplicated.

**Closed by leits** 2022-10-14 19:26 UTC
Labels: feature
