### ISSUE TITLE
Bug: Automatic join next event meeting opens multiple tabs at various times

### ISSUE THREAD

**Issue by untitled500** [leits/MeetingBar#585] opened 2023-02-14 16:52 UTC
### macOS version

13.1 (22C65)

### MeetingBar version

4.2.2

### Installation source

AppStore

### Calendars provider

macOS Calendar app

### Bug description

Automatic join next event meeting set to 1 minute.
Sometimes 2-3 tabs are opened at various times. While it is hard to discern a pattern, they appear to be -3 minutes, -1 minute, 0 minutes, +4 minutes.

### Reproduction steps

See following settings.

<img width="699" alt="image" src="https://user-images.githubusercontent.com/59500937/218803328-30a6a8c8-1dbd-4153-8dc8-4a3296066d6d.png">

<img width="698" alt="image" src="https://user-images.githubusercontent.com/59500937/218803119-045529f7-2b19-4cef-9a51-724ad3f77634.png">

<img width="697" alt="image" src="https://user-images.githubusercontent.com/59500937/218803666-603d564d-2041-4bbe-aff2-55b834d74f9f.png">

### Expected behavior

Just one instance of the meeting is opened.

**Comment by jgoldhammer** [comment] 2023-03-13 21:14
Hi @untitled500  - I cannot reproduce it at the moment. Can you please check the latest version? If the error still occurs, can you send us some sample events where this happens?

Additionally please execute following cli command on your machine.
`defaults read leits.MeetingBar`

Can you please send the output here?

**Comment by untitled500** [comment] 2023-03-21 17:20
I am on Ver 4.3 but it still seems to be happening. I tried to identify which events - but it seems to be every event. Do you need event title?

```
{
    "KeyboardShortcuts_openMenuShortcut" = "{\\"carbonModifiers\\":256,\\"carbonKeyCode\\":44}";
    "NSStatusItem Preferred Position Item-0" = 290;
    appVersion = "4.3.0";
    automaticEventJoin = 1;
    automaticEventJoinTime = 60;
    browsers = "[{\\"path\\":\\"\\\\/Applications\\\\/Firefox.app\\",\\"arguments\\":\\"\\",\\"name\\":\\"Firefox\\",\\"deletable\\":true},{\\"path\\":\\"\\\\/Applications\\\\/Google Chrome.app\\",\\"arguments\\":\\"\\",\\"name\\":\\"Google Chrome\\",\\"deletable\\":true},{\\"path\\":\\"\\\\/System\\\\/Volumes\\\\/Preboot\\\\/Cryptexes\\\\/App\\\\/System\\\\/Applications\\\\/Safari.app\\",\\"arguments\\":\\"\\",\\"name\\":\\"Safari\\",\\"deletable\\":true},{\\"path\\":\\"\\\\/Applications\\\\/Tor Browser.app\\",\\"arguments\\":\\"\\",\\"name\\":\\"Tor Browser\\",\\"deletable\\":true}]";
    createMeetingService = "\\"Google Meet\\"";
    defaultBrowser = "{\\"path\\":\\"\\",\\"arguments\\":\\"\\",\\"name\\":\\"Default web browser\\",\\"deletable\\":true}";
    dismissedEvents = "[]";
    eventStoreProvider = "\\"MacOS Calendar App\\"";
    eventTimeFormat = "\\"show\\"";
    eventTitleIconFormat = "\\"no_online_session\\"";
    filterEventRegexes = "[\\"\\Ud83c\\Udf54\\"]";
    isInstalledFromAppStore = 1;
    joinEventNotificationTime = 180;
    launchAtLogin = 1;
    meetBrowser = "{\\"path\\":\\"\\\\/Applications\\\\/Google Chrome.app\\",\\"arguments\\":\\"\\",\\"name\\":\\"Google Chrome\\",\\"deletable\\":true}";
    onboardingCompleted = 1;
    pastEventsAppereance = "\\"show_inactive\\"";
    processedEventsForAutoJoin = "[{\\"id\\":\\"E637BCC7-52A3-4C90-A2B1-D8E7EC95C6AE\\",\\"lastModifiedDate\\":640099525,\\"eventEndDate\\":701121600}]";
    processedEventsForRunScriptOnEventStart = "[]";
    selectedCalendarIDs = "[\\"5F47E50B-5418-4C0D-8776-BBECE42FB311\\",\\"5295F061-7F3F-4FA2-83C6-42BA836302D5\\",\\"C9358A23-05F3-4936-BF3C-52A756B88D00\\",\\"743598F6-F13F-41F3-A530-8AA0EBF138D2\\",\\"6FBADD97-0C4A-4744-AAA0-2D21D19F3617\\"]";
    showEventDetails = 1;
    showEventMaxTimeUntilEventEnabled = 1;
    showEventsForPeriod = "\\"today_n_tomorrow\\"";
    timeFormat = "\\"12-hour\\"";
}
```

**Comment by sumpg41** [comment] 2023-06-22 12:57
I am on MB v4.4.0, MacOS 13.2.1 and am constantly experiencing this issue

**Comment by leits** [comment] 2023-07-05 16:17
Included fix for this issue to the next release scope!
+ ref: https://github.com/leits/MeetingBar/issues/628

**Closed by leits** 2023-07-05 16:17 UTC
Labels: bug, question, under discussion
