### ISSUE TITLE
Bug: Dimmed text color in Dark theme does not match rest of bar

### ISSUE THREAD

**Issue by Sergio-Mira** [leits/MeetingBar#314] opened 2021-08-17 08:38 UTC
**App version**
Current version (3.6.0)

**Describe the bug**
When the screen is not active all the bar icons and text are dimmed. However, the dimmed color of text in Meeting Bar is less readable and does not match the rest.

**To Reproduce**
1. Setup 2 screens
2. Set Dark theme in MacOS
3. Click in one of the monitors
EXPECTED: Dimmed text color in the other monitor matches the rest of the bar

**Screenshots**
![Screenshot 2021-08-17 at 09 40 52](https://user-images.githubusercontent.com/2519238/129692916-d653d57b-0637-44fc-a7f1-d4739f6952ff.png)

**Desktop:**
 - macOS version: 11.5.1

(Thanks for this amazing app btw, it has improved my productivity quite a lot! ❤️ )

**Comment by Sergio-Mira** [comment] 2021-08-19 13:11
Color seems to be #232545 but I couldn't find it anywhere in the source.

**Comment by jgoldhammer** [comment] 2021-08-22 19:41
Thanks Sergio. I can confirm this problem. I will investigate the root cause of this color UX issue.

**Comment by jamtur01** [comment] 2022-04-22 17:27
Not sure if this is related but the text is very stark white (4.0.3) and quite hard to read. I can't find an option to change it.

<img width="316" alt="Screen Shot 2022-04-22 at 1 26 40 PM" src="https://user-images.githubusercontent.com/4365/164764451-ab11695f-4ee9-480a-830a-e6ea53931dde.png">

**Comment by jgoldhammer** [comment] 2022-04-22 17:29
Yes, I have changed it to white. Maybe we need a different solution for light and dark mode?

**Comment by jamtur01** [comment] 2022-04-22 17:30
I think so - the white looks great in dark mode:

<img width="349" alt="Screen Shot 2022-04-22 at 1 30 15 PM" src="https://user-images.githubusercontent.com/4365/164764971-1434573c-e2dd-4bb1-95f4-1de49d27064c.png">

**Comment by leits** [comment] 2022-05-06 15:59
Fixed in 4.0.

**Closed by leits** 2022-05-06 15:59 UTC
Labels: bug

**Comment by jamtur01** [comment] 2022-05-06 16:03
@leits Should I open a new issue for the dual colors for dark/light mode?

**Comment by jamtur01** [comment] 2022-05-06 16:04
Ah nm - spotted #9b85e8bc541b405742c211325d5bfa2ac679a0e8

**Comment by Sergio-Mira** [comment] 2022-07-06 10:49
This is happening again in the latest version 4.0.5
![Screenshot 2022-07-06 at 12 48 35](https://user-images.githubusercontent.com/2519238/177533818-e100b71d-cb73-4e4c-a40a-7862e031c887.png)

**Comment by Sergio-Mira** [comment] 2022-07-06 10:52
The fix looks to have been somehow reverted:
https://github.com/leits/MeetingBar/pull/436/files
https://github.com/leits/MeetingBar/blame/master/MeetingBar/StatusBarItemController.swift#L238
