### ISSUE TITLE
Bug: Can't click on any field in Preferences > All Shorcuts

### ISSUE THREAD

**Issue by kriskhaira** [leits/MeetingBar#279] opened 2021-06-05 17:43 UTC
**App version**

3.4.0

**Describe the bug**

Preferences > All Shortcuts window doesn't allow me to click in any of the fields which have the placeholder "Record Shortcut".

**To Reproduce**

1. Go to 'Preferences'
2. Click on 'All Shortcuts'
3. Try to click on any Record Shortcut field
4. Nothing happens.

**Expected behavior**

You should be allowed to record a new shortcut.

**Screenshots**

![Screenshot 2021-06-06 at 1 39 37 AM](https://user-images.githubusercontent.com/80577/120900642-80848900-c668-11eb-8a2c-f84e37990f0e.png)

**Desktop (please complete the following information):**
 - macOS version: [e.g. 10.15.7]

**Comment by jgoldhammer** [comment] 2021-06-06 12:08
Hi @kriskhaira ,

thanks for your bug report. 

Can you please send us the default values of Meetingbar?
Please run following command on the terminal and upload the file to use

`
defaults read leits.meetingbar > meetingbar_default_values.txt
`

After that please try to delete the default values for meetingbar- by executing this command you have to reconfigure meetingbar from scratch...

`
defaults delete leits.meetingbar
`

Maybe this will work. 
Currently there is no condition to disable the button in our code.

![image](https://user-images.githubusercontent.com/3872101/120923605-c9bbf380-c6cf-11eb-8469-2edf5da094f5.png)

Maybe we run into https://github.com/sindresorhus/KeyboardShortcuts/issues/41 
 of the used KeyboardShortcuts library. This is fixed in https://github.com/sindresorhus/KeyboardShortcuts/pull/43.

@leits - we should try to upgrade to the newest version I guess and recheck again.

Unfortunately I cannot reproduce locally as I am using Big Sur...

Thanks

**Closed** 2021-07-10 22:32 UTC
Labels: bug

**Comment by angel-urena** [comment] 2022-02-16 00:06
I'm having the same issue on 10.15.7
