### ISSUE TITLE
Bug: Consistent "Ouch! Can't join the ... meeting - Link not found, or your meeting service is not yet supported"

### ISSUE THREAD

**Issue by vramdal** [leits/MeetingBar#462] opened 2022-05-24 06:55 UTC
**App version**
4.0.5

**Installation source**
Downloaded from https://github.com/leits/MeetingBar/releases/tag/v4.0.5

**Describe the bug**
Consistently getting "Ouch! Can't join the ... meeting - Link not found, or your meeting service is not yet supported"
This is happening on meeting events with links to Google Meet, Whereby and Teams (at least).

**To Reproduce**
1. Create a meeting in Calendar.app, link to a Google Meeting (e.g. https://meet.google.com/ygu-nscz-udy) 
2. Wait a minute for the meeting to appear in MeetingBar
3. Click on the MeetingBar menu bar item
3. Click on the Google Meet meeting

**Expected behavior**
A web browser opens with the URL of the Google Meet meeting

**Actual behaviour**
A notification saying "Ouch! Can't join the ... meeting - Link not found, or your meeting service is not yet supported". No web browser opens.

**Desktop (please complete the following information):**
 - macOS Monterey 12.3.1

**Comment by jubr** [comment] 2022-10-06 10:49
+1 on this. Very happy (relatively new) MeetingBar user!
Same error seems to be given when no link is in the meeting. So this also happens on the time blocks I put in my agenda to prevent other people of booking meetings during that time. Hope this one is easy to fix 🤞

**Comment by leits** [comment] 2022-10-17 16:23
Hi @jubr,
If you click on the event without a link you get this notification. It's by design behavior and it literally says that there is no link to any supported service. 😅

**Comment by jubr** [comment] 2022-10-20 08:27
@leits I think I figured out why it was showing up without me clicking: it's the Automatic Join feature combined with not having a meeting link (or unsupported url format).

Would it perhaps be possible to not show the Ouch! error if there is no meeting link?

**Comment by leits** [comment] 2022-10-20 11:43
@jubr No problem 👍 
Glad to see you found a reason. Yeah, it makes sense. Also, there are feature requests to skip maybe calls (#489) and declined.

**Comment by jubr** [comment] 2022-10-20 13:22
Hmm.. looks like you already check `.meetingLink` for `nil` in 
https://github.com/leits/MeetingBar/blob/4e74e096e701469976245b388d0cf23b8cb15d10/MeetingBar/ActionsOnEventStart.swift#L69

Could it be that the value for `.meetingLink` is some other form of Falsy, like for instance `""`?

**Comment by jubr** [comment] 2022-10-21 13:33
I assumed it would auto-update and that I automagically would have the latest version. That much trust I have in MeetingBar ;)
I just updated to v4.1.0 - noticed the bugfix in the changelog. Tnx!

**Comment by leits** [comment] 2022-10-21 21:37
Since no one else has reported the original issue, I will close this ticket. Feel free @@vramdal to reopen the issue again.

**Closed by leits** 2022-10-21 21:37 UTC
Labels: bug, question
