### ISSUE TITLE
Bug: When joining a meeting early, MeetingBar tries to open the same meeting again 

### ISSUE THREAD

**Issue by jonathandieu** [leits/MeetingBar#664] opened 2023-10-26 15:16 UTC
### macOS version

14.0 (23A344)

### MeetingBar version

4.6.0

### Installation source

AppStore

### Calendars provider

Google Calendar

### Bug description

When I open a meeting link manually (to get a head start on a meeting or to open it early), the link reopens and unfocuses my screen e.g takes me to the already-open meeting's zoom link in the browser.

### Reproduction steps

1. Click on the meetingbar meeting early from the Mac menu bar
2. Join the meeting
3. Same meeting will try to open again once the scheduled time rolls around

### Expected behavior

Ideally, if the meeting has already been clicked on / opened, it would not try to automatically open the meeting again.

### Additional context

This may very well be intended/expected behavior- please let me know if this would be better suited to a feature request :)

I really love the auto-opening functionality that exists as part of the app; super convenient ❤️

**Comment by josephgruber** [comment] 2023-11-16 22:08
Same. Not daily but often at least.

**Comment by leits** [comment] 2024-03-23 16:27
Hi @jonathandieu,
Thanks for the feedback! Y
es, this is an intended behavior so an accidental click or shortcut does not prevent the expected auto-join. I understand that this trade-off may not be convenient for some users, but it warns of problems for other users and keeps behavior explicit.

I'm inclined to close this ticket because I rarely get asked about this behavior and I don't see a better solution here. Sorry!

**Closed by leits** 2024-03-23 16:27 UTC
Labels: bug
