### ISSUE TITLE
Bug: White not-a-window overlaying screen periodically

### ISSUE THREAD

**Issue by nikjft** [leits/MeetingBar#346] opened 2021-09-21 16:11 UTC
**App version**

3.8

**Describe the bug**

Occasionally after MB has been open for a while, I end up with a blank white box overlaying part of my screen. Seems like it might be a window with nothing inside it, but it doesn't actually block anything - I can click through it.

Quitting and restarting MB makes it go away, but it'll appear again.

Running MacoS Catalina

**To Reproduce**

Open MB
Wait for a while

**Expected behavior**

This shouldn't show up

**Screenshots**

I have no screenshots

**Desktop (please complete the following information):**

Catalina, 10.15.7

**Comment by leits** [comment] 2021-09-23 17:25
Thanks for the report, @nikjft!

This is a very strange problem, and hear about it for the first time and can't reproduce.
Are you sure it's related to MeetingBar?

Please, take a screenshot when it reproduces again.
Thanks!

**Comment by leits** [comment] 2021-11-20 17:40
Two months without an answer, so I'll close it for now.

**Closed by leits** 2021-11-20 17:40 UTC
Labels: bug
