### ISSUE TITLE
Abbreviate menu bar text to make more concise 

### ISSUE THREAD

**Issue by sn0wyfall** [leits/MeetingBar#41] opened 2020-08-01 04:47 UTC
The app takes a lot of space in the menu. IMO a better use of space would be to write "8h" instead of "8 hours" or "52m" instead of "52 minutes."

**Comment by leits** [comment] 2020-08-01 09:50
@sn0wyfall thanks for the feature requests!
But it's duplicate of #35, follow it for getting updates!

**Closed by leits** 2020-08-01 09:50 UTC
