### ISSUE TITLE
Bug: Upcoming event notification used title of the wrong event

### ISSUE THREAD

**Issue by brikr** [leits/MeetingBar#503] opened 2022-09-09 17:04 UTC
**App version**
4.0.6

**Installation source**
- AppStore

**Describe the bug**
Meeting notification had wrong event title

**To Reproduce**
Only had this happen once, but I think it was something like this:
1. Have an event on your calendar that is about to hit its notification time (e.g. 1 minute notifications enabled, we are 2 minutes from the event happening). I'll call this Event A
2. Create a new event that will happen later in the day (in my scenario it was the next event for the day after the upcoming event). I'll call this Event B
3. When Event A's notification should happen, the notification has Event B's title

**Expected behavior**
The notification should have the title of the event that is actually about to start

**Desktop (please complete the following information):**
 - macOS version: 12.5.1

**Additional context**
Other info that might be relevant:
- The calendar in question was an Exchange account added via macOS internet accounts
- In my case, Event B was happening 2 hours from now, and one of the guests was in a timezone that is 2 hours ahead. So Event A (actually about to occur) was going to happen at 10am for _me_, and Event B (happening in two hours but got notification anyway) was going to happen at 10am for _the guest_.

**Comment by leits** [comment] 2022-10-16 13:56
Thanks for the report, @brikr!
This is very strange. Also, no one else reported it, and I couldn't reproduce it.

Did it happen to you again after the report?

**Comment by leits** [comment] 2022-10-21 17:47
As there was no feedback, I will close the issue now. Feel free @brikr to reopen the issue again.

**Closed by leits** 2022-10-21 17:47 UTC
Labels: bug, question
