### ISSUE TITLE
auto-join only accepted meetings

### ISSUE THREAD

**Issue by staubda** [leits/MeetingBar#616] opened 2023-04-28 18:04 UTC
It would be great if there was a setting that could let you only auto-join meetings that you've accepted. Currently (as far as I can tell) auto-join forces me to join meetings I haven't confirmed I'll attend. Thanks!

**Comment by leits** [comment] 2023-07-05 21:25
Thanks for the request, @staubda 

I'll close this one as a duplicate of existing #608

**Closed by leits** 2023-07-05 21:25 UTC
Labels: duplicate, feature

**Comment by staubda** [comment] 2023-07-05 23:03
@leits is this a duplicate? at a glance it seems like a completely different issue to me

**Comment by leits** [comment] 2023-07-06 12:04
Sorry, wrong link!
https://github.com/leits/MeetingBar/issues/604
