### ISSUE TITLE
Bug: Incorrect time to next meeting showing

### ISSUE THREAD

**Issue by nevadascout** [leits/MeetingBar#181] opened 2021-02-09 21:36 UTC
App version `3.0.0`
MacOS version `11.1` Big Sur

This is going to be a pretty useless bug report but I want to report it anyway to give you some awareness of it.

I noticed today that the countdown timer showing in the menu bar next to the meeting had an incorrect time. It was frozen on `in 10 minutes` when the meeting actually started in 1 minute's time.

I'm not sure how to reproduce this, but I fixed it by quitting and restarting the MeetingBar app.

My mac was working a bit hard (the fans were spinning loudly) so maybe higher CPU load has something to do with it?

Sorry I can't give any more information :/

**Comment by jgoldhammer** [comment] 2021-02-09 22:09
I have noticed this also during the last time and also with version 2.0.5! Currently I have no idea how to fix this...

**Comment by Quartzic** [comment] 2021-02-16 16:59
Also experiencing this issue after updating from v2 to v3.

**Comment by Yago** [comment] 2021-03-11 08:06
Worst, new meetings don't appear in MeetingBar...

I'm also on **Big Sur** with `3.1.2`

**Comment by nevadascout** [comment] 2021-03-11 08:14
@Yago I've found that new meetings sometimes take a while to appear in MeetingBar. It must be something to do with how meetings sync

**Comment by leits** [comment] 2021-03-11 14:46
@Yago, can you check the Calendar app? Do they appear there?

**Comment by Yago** [comment] 2021-03-11 15:24
@leits Very nice guess! No, it didn't. After moving on Big Sur recently, the session must have been revoked. And because I'm only using the Calendar App for MeetingBar (browser tabs are my go to), I didn't see the alert...

**Comment by RaiserWeb** [comment] 2021-03-15 18:01
I see meeting = (now) when it actually still has 1 minute to start.

**Comment by jamtur01** [comment] 2021-03-24 18:26
Same problem with time freezing. Requires to restart of MeetingBar to update. MacOS 11.2.3 and MeetingBar 3.1.2.

**Comment by leits** [comment] 2021-03-24 19:41
Spend a few hours loading CPU/RAM on my mac to reproduce. I can't reach a complete freeze.
@jamtur01, could you, please, get MeetingBar logs from Console when it freezes next time?

For updating the status bar title we use `NSBackgroundActivityScheduler` recommended by Apple.
With the highest priority - "User Interactive" - and 30 seconds interval.

From what I did manage to reproduce, macOS may not run these tasks if the system is currently heavily loaded - 90% + CPU or memory overflow. But as soon as the load drops to the limit, the following tasks are started.

I will halve the frequency to 15 seconds, maybe it will help too.

@jgoldhammer, jfyi

**Comment by leits** [comment] 2021-03-24 19:46
I also have one strange assumption.
@jamtur01 or anyone else here, could you also check if the menu events are updated when frozen? For example, if you add a new event to your calendar, will it appear? 
Thanks!

**Comment by jgoldhammer** [comment] 2021-03-24 19:52
We could try to wrap the update code in the activityhandler into DispatchQueue.main.async  which means to run the update in the Main Thread.

**Comment by jamtur01** [comment] 2021-03-24 20:02
@leits It appears new events are added. I am unclear what the normal tempo for them to be polled from Calendar but it looks like 5 ish minutes?

I do see these events in the Console

```
default	16:01:42.749634-0400	dasd	501:leits.MeetingBar.updatestatusbartitle:AA3AF3:[
	{name: ThermalPolicy, policyWeight: 5.000, response: {Decision: Absolutely Must Not Proceed, Score: 0.00, Rationale: [{thermalLevel >= 2}]}}
 ], FinalDecision: Absolutely Must Not Proceed}
default	16:01:42.750341-0400	dasd	501:leits.MeetingBar.updateevents:E99813:[
	{name: ThermalPolicy, policyWeight: 5.000, response: {Decision: Absolutely Must Not Proceed, Score: 0.00, Rationale: [{thermalLevel >= 2}]}}
 ], FinalDecision: Absolutely Must Not Proceed}
default	16:01:53.060137-0400	dasd	501:leits.MeetingBar.updatestatusbartitle:AA3AF3:[
	{name: ThermalPolicy, policyWeight: 5.000, response: {Decision: Absolutely Must Not Proceed, Score: 0.00, Rationale: [{thermalLevel >= 2}]}}
 ], FinalDecision: Absolutely Must Not Proceed}
default	16:01:53.060656-0400	dasd	501:leits.MeetingBar.updateevents:E99813:[
	{name: ThermalPolicy, policyWeight: 5.000, response: {Decision: Absolutely Must Not Proceed, Score: 0.00, Rationale: [{thermalLevel >= 2}]}}
 ], FinalDecision: Absolutely Must Not Proceed}
```

**Comment by leits** [comment] 2021-03-24 20:17
> We could try to wrap the update code in the activityhandler into DispatchQueue.main.async which means to run the update in the Main Thread.

I thought about that, too, @jgoldhammer. Is that what you mean? https://github.com/leits/MeetingBar/commit/eae120b11179d0cee651c8fe76cb10d86607c59e

**Comment by leits** [comment] 2021-03-24 20:19
@jamtur01, macOS blocks the app from updating because your laptop is overheating.
I don't think it can be bypassed at all.

**Comment by jamtur01** [comment] 2021-03-24 20:20
@leits Yeah I figured from the console error. What's weird is the temperature sensor reports 50-60 degrees which should be within tolerances and not trigger the thermal throttling. :(

**Comment by jgoldhammer** [comment] 2021-03-24 20:23
> > We could try to wrap the update code in the activityhandler into DispatchQueue.main.async which means to run the update in the Main Thread.
> 
> I thought about that, too, @jgoldhammer. Is that what you mean? [eae120b](https://github.com/leits/MeetingBar/commit/eae120b11179d0cee651c8fe76cb10d86607c59e)

Maybe we have to add the completion statement into the async block as well . I do not what happens when completion is executed earlier than the UI update...

**Comment by jgoldhammer** [comment] 2021-03-24 20:26
Und we have to think about the other methods which trigger the update like a settings change. They have to run in UI thread as well IMHO...

**Comment by leits** [comment] 2021-03-24 20:29
> And we have to think about the other methods which trigger the update like a settings change. They have to run in UI thread as well IMHO...

Maybe, but I don't see an easy way to implement it.


While I'm thinking about updating the status of the bar, this is the main problem.
Maybe it's worth moving to Timer?
https://www.hackingwithswift.com/articles/117/the-ultimate-guide-to-timer

**Comment by leits** [comment] 2021-03-24 20:32
Thank you a lot, @jamtur01.
After your help, I am sure that the current approach to update the title can't solve this problem.

Please, tell me more, how often do you have this problem?
And could you help us and check a test build when it's ready?

**Comment by jamtur01** [comment] 2021-03-24 20:36
@leits Probably happens 3-4 times a day. I'll tweak my fan control a bit.

Also happy to test a build.

**Comment by jgoldhammer** [comment] 2021-03-31 20:23
I guess we should switch to Timer base  implementation (https://developer.apple.com/documentation/foundation/timer) instead of the  NSBackgroundActivityScheduler which schedules low priority tasks in the background.
What do you think @leits ? It is worth to try it? I guess NSBackgroundActivityScheduler cannot be tweak more than we have done it...

**Comment by nevadascout** [comment] 2021-04-01 09:58
This is particuarly bad with Zoom which is a huge CPU resource hog when it's open and often is showing the incorrect remaining time of a meeting because of this thermal throttling issue.

It would be great to have this fixed :)

**Comment by defrex** [comment] 2021-04-09 12:57
This problem went away for me! 🎉 

I suspect it was related to a recent Big Sur update.

**Comment by jamtur01** [comment] 2021-04-09 13:25
@defrex What MacOS version are you on?

**Comment by defrex** [comment] 2021-04-09 15:44
I'm on `11.2.3`, ya. I can't say for sure what happened, but MeetingBar seems to work fine after my computer booted from that update.

**Comment by jgoldhammer** [comment] 2021-04-16 06:46
I have made some changes regarding the scheduling with the timer implementation. I hope, this will finally solve the issue for all.

**Closed** 2021-04-16 17:08 UTC
Labels: bug

**Comment by nevadascout** [comment] 2021-04-30 09:02
I'm still seeing this problem on MeetingBar v3.2.2

**Comment by defrex** [comment] 2021-04-30 19:54
This has regressed for me as well. Also on v3.2.2

**Comment by leits** [comment] 2021-04-30 20:46
Sorry, @nevadascout, @defrex. 3.2.2 was only a quick release to fix MeetingBar crashing.
But I'm already preparing a new major release!

**Comment by leits** [comment] 2021-05-01 08:34
Prepared a prerelease build. @jamtur01, @nevadascout, @defrex, could you, please, check that everything works now?
https://github.com/leits/MeetingBar/releases/tag/v3.3.0

**Comment by jamtur01** [comment] 2021-05-01 16:40
Am running it now - will report results.

**Comment by jamtur01** [comment] 2021-05-03 20:16
Looks good so far. Seems to have resolved the issue for me.

**Comment by leits** [comment] 2021-05-03 20:22
Awesome, thanks!

I have started a phased release in AppStore and will publish an update in homebrew on Wednesday/Thursday. So, it should be available for all by the end of the week if there are no problems.
