### ISSUE TITLE
Add authuser to url

### ISSUE THREAD

**Issue by sirupsen** [leits/MeetingBar#34] opened 2020-07-29 23:51 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I am logged into multiple Google Accounts for Meet. Ideally, it'd figure out which one owns an event, and then add `?authuser=$email` to the URL to avoid users having to switch manually. 

**Describe alternatives you've considered**
This seems like the simplest solution.

**Additional context**

**Comment by dansiemens** [comment] 2020-07-30 03:15
Duplicate of #24

**Comment by BrandonSmith** [comment] 2020-09-25 01:11
Seems this is available in latest release. Right?

**Comment by Itaybre** [comment] 2020-09-25 02:15
@BrandonSmith you are right, it was merged for 1.5

@leits please close this issue

**Comment by leits** [comment] 2020-09-25 06:52
Thanks, @BrandonSmith, @Itaybre. Closed.

**Closed by leits** 2020-09-25 06:52 UTC
Labels: enhancement
