### ISSUE TITLE
The application can't be opened. (Startup error)

### ISSUE THREAD

**Issue by wayneashleyberry** [leits/MeetingBar#85] opened 2020-09-30 13:51 UTC
**Describe the bug**

I have installed Meeting Bar using homebrew, and it runs just fine. However, if I restart my machine or log out and back in I get a cryptic error message "The application can't be opened. -50".

I then have to open Meeting Bar manually, which works fine.

**To Reproduce**

Install Meeting Bar, enable "Launch at Login" and then log out and back in again.

**Expected behavior**

This error should not appear and Meeting Bar should open on startup.

**Screenshots**

<img width="488" alt="Screenshot 2020-09-30 at 14 45 04" src="https://user-images.githubusercontent.com/727262/94693525-be881b00-032b-11eb-89dc-263fe3ff43ec.png">

**Desktop (please complete the following information):**

```
                 -/+:.          wayne@Waynes-iMac
                :++++.          OS: 64bit Mac OS X 10.15.7 19H2
               /+++/.           Kernel: x86_64 Darwin 19.6.0
       .:-::- .+/:-``.::-       Uptime: 44m
    .:/++++++/::::/++++++/:`    Packages: 107
  .:///////////////////////:`   Shell: fish 3.1.2
  ////////////////////////`     Resolution: 6400x3600
 -+++++++++++++++++++++++`      DE: Aqua
 /++++++++++++++++++++++/       WM: Quartz Compositor
 /sssssssssssssssssssssss.      WM Theme: Blue
 :ssssssssssssssssssssssss-     Disk: 11G / 1.0T (2%)
  osssssssssssssssssssssssso/`  CPU: Intel Core i7-10700K @ 3.80GHz
  `syyyyyyyyyyyyyyyyyyyyyyyy+`  GPU: AMD Radeon Pro 5500 XT
   `ossssssssssssssssssssss/    RAM: 10084MiB / 32768MiB
     :ooooooooooooooooooo+.
      `:+oo+/:-..-:/+o+/-
```

**Additional context**

I tried removing everything from launch agents, and all other startup items to eventually get to this. I can safely reproduce the error message on startup by uninstalling and reinstalling Meeting Bar.

**Comment by leits** [comment] 2020-09-30 14:36
Thanks, @wayneashleyberry!

@jogendra , @Itaybre can you take a look at this issue?

**Comment by jogendra** [comment] 2020-09-30 14:40
Hey @leits! Let me take a look.

Are you also facing the same issue? (and updated to latest version?) @leits @Itaybre

**Comment by Itaybre** [comment] 2020-09-30 14:42
Saw this today (I don't restart my machine frequently) but MeetingBar did open automatically

**Comment by jogendra** [comment] 2020-09-30 14:46
Most probably the reason would be the Development Team for the AutoLauncher is not set when you released (the bundle homebrew fomaula using). As I was not able to set (do not have paid membership). That would probably fix. If not, I will do my part.

**Comment by leits** [comment] 2020-09-30 15:11
@jogendra, Now the target has been signed and it happened earlier than the previous release.
https://github.com/leits/MeetingBar/compare/v1.6.1...master

**Comment by jogendra** [comment] 2020-09-30 15:17
@wayneashleyberry please update to latest version, `1.6.1`. It should fix your issue.

To update, run:

```bash
brew upgrade meetingbar
```

Still not get fixed, try running `brew reinstall meetingbar` after upgrading.

**Comment by jogendra** [comment] 2020-09-30 15:19
@leits we should also put/ask meetingbar version in issue templete. It will help us getting better idea, which version having the issue.

**Comment by wayneashleyberry** [comment] 2020-09-30 15:51
@jogendra tried both of those and still get the same issue. Removed it completely, did a cleanup, installed afresh and still the same. Pretty sure I was already running on `v1.6.1` as well 🤷

**Comment by jogendra** [comment] 2020-10-06 06:33
@wayneashleyberry oh so sorry to know that it didn't work. Let me look into this earliest.

**Comment by jogendra** [comment] 2020-10-07 12:49
Hey @leits @wayneashleyberry 
I just figured out what causing the issue and fix to it. Problem was with previous implementation. Opening a PR for the fix, today only.

**Comment by marcusziade** [comment] 2020-10-17 05:33
I'm still getting this crash after updating to 1.6.1 😢

**Comment by jogendra** [comment] 2020-10-18 04:15
@marcusziade new release has not been made after the merging of PR above. Hopefully, it will be released soon. I am sure this will fix your issue.

**Comment by marcusziade** [comment] 2020-10-27 07:08
Any update on this?

**Comment by leits** [comment] 2020-11-06 18:14
Sorry for the delay, guys!
Fixed version here and on homebrew available here and on homebrew:
https://github.com/leits/MeetingBar/releases/tag/v1.6.2
The AppStore version is on review.

**Closed** 2020-11-20 16:26 UTC
Labels: bug

**Comment by tonglil** [comment] 2021-09-30 20:53
Mm, as a new MeetingBar user, I am encountering this when I click on an event that doesn't have a meeting link (aka a regular calendar event).

FWIW, the event is on an iCloud calendar I own.

The application can’t be opened. -50
<img width="532" alt="Screen Shot 2021-09-30 at 1 52 17 PM" src="https://user-images.githubusercontent.com/3250776/135528389-fc3de497-48d2-4d37-8d21-361f99abbbce.png">

**Comment by jogendra** [comment] 2021-10-01 08:41
@tonglil Seems like a similar issue. I think most probably the API for Launch at Login changed so it is giving an error. Have to wait for few more reports to know the cause.
