### ISSUE TITLE
Feature: open meetings in Google Meet PWA if available

### ISSUE THREAD

**Issue by stplva** [leits/MeetingBar#747] opened 2024-07-18 12:44 UTC
### Issue that this suggestion fixes

Currently, users with installed PWA of Google Meet aren't able to open Google Meet meetings directly in the PWA, and instead the meetings are opened in the chosen browser. This PWA is very convenient and should be treated the same way as other desktop applications – Zoom or Teams.

### Solution description

It would be nice to add another option to the settings to open the Google Meet meetings in the PWA, if it's installed. If not, this option can either be unavailable, or it will fallback to the default browser.

### Alternatives considered

The feature can be added only if there's a PWA installed.

**Comment by leits** [comment] 2024-07-29 11:26
Hi @stplva!
Sorry, but Google Meet PWA still can't open a certain event from the URL 😞 

duplicate of #601 #481 #409 #313

**Closed by leits** 2024-07-29 11:26 UTC
Labels: duplicate, feature
