### ISSUE TITLE
Feature: Integration directly with Google Calendar

### ISSUE THREAD

**Issue by leobenkel** [leits/MeetingBar#177] opened 2021-02-09 11:43 UTC
Hello,

**Is your feature request related to a problem? Please describe.**

My problem is that I do not want to link my google account to my apple account with the osx Calendar app

**Describe the solution you'd like**

I would like to be able to connect with Google account directly with your app without going through the osx Calendar app

**Describe alternatives you've considered**

No alternative in mind

**Additional context**

The UI would just have an option to connect to Calendar like it does today and an other to add as many Google account as desired , that will open the google login page and then select which calendars need to be read. 

Thank you !

**Comment by leobenkel** [comment] 2021-02-09 11:44
Related to https://github.com/leits/MeetingBar/issues/158

**Comment by jgoldhammer** [comment] 2021-02-09 12:29
Hi, thanks for your feature request. I will close as duplicate of #158 . Thanks

**Closed by jgoldhammer** 2021-02-09 12:29 UTC
Labels: feature
