### ISSUE TITLE
Bug: MeetingBar consistently disappearing from the menu bar

### ISSUE THREAD

**Issue by annaderengowski** [leits/MeetingBar#684] opened 2024-01-31 17:40 UTC
### macOS version

14.1.1

### MeetingBar version

4.7

### Installation source

AppStore

### Calendars provider

Google Calendar

### Bug description

I recently stopped getting notifications 1 minute before meetings, and noticed MeetingBar was missing from my menu bar. When I start MeetingBar from spotlight, it returns to the menu bar, but then disappears shortly after. I haven't yet figured out if there is a pattern to when it gets removed from the menu bar.

**Comment by jvacek** [comment] 2024-02-08 12:03
Do you have a mac with a notch? It could be "hiding" behind the notch because of MacOS behaviour. If that's the case, you can shorten the length of the event title in settings.

**Comment by annaderengowski** [comment] 2024-02-08 15:54
> Do you have a mac with a notch? It could be "hiding" behind the notch because of MacOS behaviour. If that's the case, you can shorten the length of the event title in settings.

I do have a Mac with a notch, but this isn't the issue. MeetingBar isn't hidden, the app just stops running. I'm not getting meeting notifications when this happens. I significantly pared down the items showing in the menu bar, viewed the menu bar on an external monitor--MeetingBar doesn't appear until I re-open the app via Spotlight.

**Comment by nitrocode** [comment] 2024-03-28 19:15
I have the same issue. I want to change the settings and the only way I can do it is by creating a false meeting in 5 minutes, then changing the setting, and then deleting the false meeting from my calendar.

**Comment by muzirian** [comment] 2024-04-24 08:01
I have the same issue, on 16in M1 pro with notch running sonoma.
Meeting bar is running in background, launching again makes no difference.
Clicking on the notch shows nothing.
But just noticed google drive has similar behavior and launching drive again opens the menu from under the notch.
But launching meeting bar isnt opening the menu.

**Comment by LouisJS** [comment] 2024-05-13 10:43
So annoying

**Comment by albertmonzo** [comment] 2024-06-17 16:13
Exact same issue, M1 Pro 16", Sonoma 14.5. When I first installed I thought it wasn't working at all, only figured it out when I saw the suggestion above of creating a fake meeting in 5 mins to force the tray item to show, then I was able to open the preferences and configure the app for the first time. Still, after the fake meeting was finished it disappeared again

**Comment by jtron9k** [comment] 2024-06-18 13:47
Same issue for me as well. 14" M1 Pro, 32GB Ram, Sonoma 14.5. FWIW InYourFace had the exact same issue this morning, so after some searching I found out about MeetingBar to try it and am having this same issue. The fact another meeting notification app that lives in the menu bar is having the same issue is interesting.

**Comment by nitrocode** [comment] 2024-06-20 16:31
I noticed something odd when upgrading meetingbar. It got unsynced from google and I was able to see the icon all the time in my meeting bar. I was very happy about this.

I did not know I was no longer logged into my google calendar until I noticed I wasn't getting the fullscreen notifications. Once I logged into my google calendar, the icon hid itself.

If I quit the meetingbar app and start it again. The icon pops up for a second in the tray which allows me to open the settings and then disappears. What's also weird, is that it appears next to the icon for [flameshot](https://github.com/flameshot-org/flameshot), and then both the meeting bar and flameshot icons disappear.

When I quit meetingbar, the flameshot icon reappears.

---

Flameshot is installed globally `/Applications/flameshot.app`
MeetingBar is installed locally `/Users/user/Applications/MeetingBar.app`

Unsure if that has anything to do with this.

**Comment by CK-Ward** [comment] 2024-06-20 18:30
Same issue here. MeetingBar works great when i have an external monitor, but otherwise it disappears, probably because the length is too long for the compact sidebar.

**Comment by sikander441** [comment] 2024-06-25 15:39
Facing similar issue, I am not seeing Meetingbar in the menu bar at all, no matter how many times I try to launch.

Apple M3 Max running on Sonoma 14.5

**Comment by bravely** [comment] 2024-06-27 15:08
Question for folks- do you have "No Icon" set for the meeting?

![Screenshot 2024-06-27 at 9 05 36 AM](https://github.com/leits/MeetingBar/assets/301293/47ba1a54-3826-41c7-b8f2-17818dcf05aa)

If you do, the app disappearing might be because when the app started up it didn't have today's events.

**Comment by rarandall** [comment] 2024-06-28 03:12
The bar was only appearing for me on external monitors due to the laptop monitor (14in MBP M1) being to narrow. I got the bar to reappear by entering setting from external monitor meetingbar, adjusting the title length to 10 characters (Preferences -> Appearance -> Title)

**Comment by leits** [comment] 2024-06-28 10:36
Hi folks!
Thanks for the reports. Unfortunately, it's not a bug and there's nothing I can do about it.

The status bar is fully managed by macOS. So, if you don't have enough space in your status bar, macOS will hide all the items that don't fit. When you restart the app, macOS can remove some other items to fit the new item. It's just a macOS behavior and can't be changed from the app side.

I recommend using apps like [Dozer](https://github.com/Mortennn/Dozer), [Bartender](https://www.macbartender.com/), or similar to clean up your status bar.

You can also change the Appearance settings for the MeetingBar to take up more space. If it is not currently displayed in the status bar, use this link to open the settings:  [meetingbar://preferences](meetingbar://preferences)

duplicate of: https://github.com/leits/MeetingBar/issues/710, https://github.com/leits/MeetingBar/issues/561, https://github.com/leits/MeetingBar/issues/613

**Closed by leits** 2024-06-28 10:36 UTC
Labels: bug

**Comment by edmundcraske2-nhs** [comment] 2024-06-28 11:06
@leits It might be that sometimes it's behaving as you state - but there's definitely some other issue meaning that MeetingBar is not running after a while for some people (like me) - as I stop getting notifications also.

**Comment by jtoy** [comment] 2024-07-16 17:35
FYI, I ran into the exact same issue. I suggest this info be added all over the app such as in the FAQ, README, etc. I hunted for a while to find this and only found it because I searched closed issues here.

**Comment by afucher** [comment] 2024-07-24 18:58
Also, could have a configuration based on the size of the screen to show or not the title. I use external monitors and works perfectly, today I have to work only in my Mac and it started to now show.
I solved with this thread, opening the settings and removing the title so it fits in the menu bar.
I can open a new issue for this suggestion, if it makes sense.

**Comment by nitrocode** [comment] 2024-08-06 14:00
This helped me by hiding icons I didn't need https://github.com/dwarvesf/hidden

**Comment by jvacek** [comment] 2024-08-06 14:20
> @leits It might be that sometimes it's behaving as you state - but there's definitely some other issue meaning that MeetingBar is not running after a while for some people (like me) - as I stop getting notifications also.

Possibly related to this? https://github.com/leits/MeetingBar/issues/656
